@url_base = http://localhost:5249/api

### Cadastrar Usuário
POST {{url_base}}/usuario/cadastrar
Content-Type: application/json

{
    "nome": "Lukinhas",
    "email": "lu@gmail.com",
    "senha": "1234567"
}

### Login Usuário
POST {{url_base}}/usuario/login
Content-Type: application/json

{
    "email": "lu@gmail.com",
    "senha": "1234567"
}

### Listar Usuários
GET {{url_base}}/usuario/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiYWRtaW5pc3RyYWRvciIsImV4cCI6MTc0NzAxODU2MX0.qg-JOnmxiXRZjKdsk4kEGXZXTlH1Ty5kqliST9rURC0


### Deletar Usuário
DELETE {{url_base}}/usuario/deletar/